name: Serverless Event Logger

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  lint-and-test:
    name: Install dependencies, Lint & Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.13
      uses: actions/setup-python@v4
      with:
        python-version: "3.13"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install uv
        uv pip install -e .[dev]

    - name: Run linter
      run: |
        ruff check .

    - name: Run tests
      run: |
        uv run pytest
