name: Serverless Event Logger

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  lint-and-test:
    name: Install dependencies, Lint & Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.13
      uses: actions/setup-python@v4
      with:
        python-version: "3.13"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install uv
        uv pip install -e .[dev] --system

    - name: Run linter
      run: |
        uv run ruff check .

    - name: Run tests
      run: |
        uv run pytest

  deploy:
    name: Deploy to AWS via CDK
    runs-on: ubuntu-latest
    needs: lint-and-test
    if: github.ref == 'refs/heads/main'
    permissions:
      id-token: write
      contents: read
    env:
      PROJECT: sls-event-logger
      STAGE: dev
      AWS_DEFAULT_REGION: ap-southeast-2
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install aws-cdk-lib aws-cdk-aws-lambda-python-alpha constructs

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions-role
          aws-region: ap-southeast-2

      - name: Install AWS CDK
        run: npm install -g aws-cdk

      - name: Deploy to AWS
        run: |
          cd infrastructure
          cdk deploy --all --require-approval never
